name: Azure Static Web Apps CI/CD (NuxtJS-Starter 2)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  repository_dispatch:
    types: [agility-content-update]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    concurrency:
      group: agility-cms-deploy-main
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Fix git permissions
        run: sudo chown -R $USER:$USER .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Cache Agility CMS & Nuxt
        uses: actions/cache@v4
        with:
          path: |
            node_modules/.cache
            node_modules/@agility/.cache
            .nuxt
          key: ${{ runner.os }}-agility-nuxt-${{ hashFiles('**/package-lock.json') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-agility-nuxt-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-agility-nuxt-

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_DUNE_026F7570F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          app_build_command: "npm run generate"
          ###### End of Repository/Build Configurations ######
        env:
          AGILITY_GUID: ${{ vars.AGILITY_GUID }}
          AGILITY_API_FETCH_KEY: ${{ secrets.AGILITY_API_FETCH_KEY }}
          AGILITY_LOCALES: ${{ vars.AGILITY_LOCALES }}
          AGILITY_SITEMAP: ${{ vars.AGILITY_SITEMAP }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_DUNE_026F7570F }}
          action: "close"
          app_location: "/"
